### ISSUE TITLE
Error from plugin after fresh new install

### ISSUE THREAD

**Issue by ayumihamsaki** [rainlab/user-plugin#392]
Here is the stack trace:

```
[04-Jul-2019 17:49:00 UTC] PHP Fatal error:  Uncaught Error: Class 'RainLab\User\Classes\UserRedirector' not found in /home/blank/public_html/plugins/rainlab/user/Plugin.php:44
Stack trace:
#0 /home/blank/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(749): RainLab\User\Plugin->RainLab\User\{closure}(Object(October\Rain\Foundation\Application), Array)
#1 /home/blank/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#2 /home/blank/public_html/vendor/laravel/framework/src/Illuminate/Container/Container.php(586): Illuminate\Container\Container->resolve('redirect', Array)
#3 /home/blank/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(732): Illuminate\Container\Container->make('redirect', Array)
#4 /home/blank/public_html/vendor/october/rain/src/Foundation/Application.php(158): Illuminate\Foundation\Application->make('redirect')
#5 /home/blank/public_html/vendor/laravel/framework/src/Illuminat in /home/blank/public_html/plugins/rainlab/user/Plugin.php on line 44
```

The above is from the `php_errorlog` file.

I am also seeing errors all the time in the `Settings > Event Log` as well.

Installed version: 1.5.0

**Comment by ayumihamsaki** [comment]
(Will try and add the stack trace from the `Settings > Event Log` as well. Sorry I deleted it before writing this issue - will wait for the event log to update in a few days time).

**Comment by ayumihamsaki** [comment]
Gonna close this and open a new issue, when I have the full stack trace. I don't believe the above is the full error.
